### ISSUE TITLE
Helm resource always deploys to the same cluster as it runs in.

### ISSUE THREAD

**Issue by strzelecki-maciek** [linkyard/concourse-helm-resource#57]
I specify: cluster_url, cluster_ca and token 

I expect that helm deployment will appear in the target cluster.

Instead the deployment goes to the cluster that concourse runs in (cluster_url seems to be ignored)

**Comment by msiegenthaler** [comment]
That seems weird to me, because we don’t have any logic regarding local Cluster in it. So I think if you leave out cluster_url it’ll never work.
Would your token work for both clusters?

I would try setting cluster_url to something non-existing to see what happens. This deploy should fail.
What you can also do is use ‚fly hijack‘ and change the common.sh script to output the generated config. The stdin for the resource gets saved to a temp file in the userhome, so you can reuse that.

**Comment by strzelecki-maciek** [comment]
Yes, a dummy cluster_url breaks the tasks as expected.
The default behaviour of kubectl is to go for local cluster, my guess is that the externally generated config is ignored. I'll try to set something up for testing it and ill report back

**Comment by strzelecki-maciek** [comment]
I forgot i had the override for HELM_HOST (because of https://github.com/linkyard/concourse-helm-resource/issues/45)
Can you tell me how i can avoid issue 45 and have multicluster deployment working at the same time?

**Comment by strzelecki-maciek** [comment]
Okay, closing. Not an issue with the resource, but with helm instead. Still i ended up creating two helm-resource-types. One for local deployment where i utilise the new helm_host config value. For external kube clusters i modified the common.sh setup script to start a kubectl port-forward, and in the target cluster created a role that is allowed to port-forward. This works well enough until helm is fixed.
